# Generated by Django 4.2.1 on 2023-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystudent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grades", name="date", field=models.DateTimeField(auto_now=True),
        ),
    ]
