# Generated by Django 4.2.1 on 2023-05-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystudent", "0002_grades_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="grades",
            name="grade_type",
            field=models.CharField(
                choices=[
                    ("lab", "Лабораторная работа"),
                    ("sem", "Семинар"),
                    ("lec", "Лекция"),
                ],
                default="sem",
                max_length=3,
            ),
        ),
    ]
