# Generated by Django 4.2.1 on 2023-05-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystudent", "0005_alter_grades_grade_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("Лабораторная работа", "Laboratory work"),
                    ("Семинар", "Seminar"),
                    ("Лекция", "Lecture"),
                    ("Сессия", "Session"),
                ],
                default="Семинар",
                max_length=20,
            ),
        ),
    ]
