# Generated by Django 4.2.1 on 2023-05-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystudent", "0003_grades_grade_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("lab", "Laboratory work"),
                    ("sem", "Seminar"),
                    ("lec", "Lecture"),
                    ("ses", "Session"),
                ],
                default="sem",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="grades", name="date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="grades",
            name="grade_type",
            field=models.CharField(
                choices=[
                    ("lab", "Laboratory work"),
                    ("sem", "Seminar"),
                    ("lec", "Lecture"),
                    ("ses", "Session"),
                ],
                default="sem",
                max_length=3,
            ),
        ),
    ]
