# Generated by Django 4.2.1 on 2023-05-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystudent", "0004_attendance_attendance_type_alter_grades_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grades",
            name="grade_type",
            field=models.CharField(
                choices=[
                    ("Лабораторная работа", "Laboratory work"),
                    ("Семинар", "Seminar"),
                    ("Лекция", "Lecture"),
                    ("Сессия", "Session"),
                ],
                default="Семинар",
                max_length=20,
            ),
        ),
    ]
