# Generated by Django 4.2.1 on 2023-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystudent", "0006_alter_attendance_attendance_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("Лабораторная работа", "Laboratory work"),
                    ("Семинар", "Seminar"),
                    ("Лекция", "Lecture"),
                    ("Сессия", "Session"),
                    ("Экзамен", "Exam"),
                    ("Зачет", "Test"),
                ],
                default="Семинар",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grades",
            name="grade_type",
            field=models.CharField(
                choices=[
                    ("Лабораторная работа", "Laboratory work"),
                    ("Семинар", "Seminar"),
                    ("Лекция", "Lecture"),
                    ("Сессия", "Session"),
                    ("Экзамен", "Exam"),
                    ("Зачет", "Test"),
                ],
                default="Семинар",
                max_length=20,
            ),
        ),
    ]
